/*
 * Agent API
 *
 * The Neuron® publishes an Agent API that can be used by agents that do not wish to, or are able to, connect to the Neuron® via any of the XMPP bindings available, such as standard binary  socket, websocket or Synchronous HTTP (BOSH). Via the Agent API, the agent is permitted to do  basic tasks, such as send messages, create Agent IDs, and sign contracts with such Agent IDs.  The Full API is 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TAG.Networking.Agent.Model;
using TAG.Networking.Agent.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TAG.Networking.Agent.Test.Model
{
    /// <summary>
    ///  Class for testing CreateKeyBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateKeyBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateKeyBody
        //private CreateKeyBody instance;

        public CreateKeyBodyTests()
        {
            // TODO uncomment below to create an instance of CreateKeyBody
            //instance = new CreateKeyBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateKeyBody
        /// </summary>
        [Fact]
        public void CreateKeyBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateKeyBody
            //Assert.IsType<CreateKeyBody>(instance);
        }

        /// <summary>
        /// Test the property 'LocalName'
        /// </summary>
        [Fact]
        public void LocalNameTest()
        {
            // TODO unit test for the property 'LocalName'
        }

        /// <summary>
        /// Test the property 'VarNamespace'
        /// </summary>
        [Fact]
        public void VarNamespaceTest()
        {
            // TODO unit test for the property 'VarNamespace'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Nonce'
        /// </summary>
        [Fact]
        public void NonceTest()
        {
            // TODO unit test for the property 'Nonce'
        }

        /// <summary>
        /// Test the property 'KeySignature'
        /// </summary>
        [Fact]
        public void KeySignatureTest()
        {
            // TODO unit test for the property 'KeySignature'
        }

        /// <summary>
        /// Test the property 'RequestSignature'
        /// </summary>
        [Fact]
        public void RequestSignatureTest()
        {
            // TODO unit test for the property 'RequestSignature'
        }
    }
}
