/*
 * Agent API
 *
 * The Neuron® publishes an Agent API that can be used by agents that do not wish to, or are able to, connect to the Neuron® via any of the XMPP bindings available, such as standard binary  socket, websocket or Synchronous HTTP (BOSH). Via the Agent API, the agent is permitted to do  basic tasks, such as send messages, create Agent IDs, and sign contracts with such Agent IDs.  The Full API is 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TAG.Networking.Agent.Model;
using TAG.Networking.Agent.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TAG.Networking.Agent.Test.Model
{
    /// <summary>
    ///  Class for testing DomainInfoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainInfoResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DomainInfoResponse
        //private DomainInfoResponse instance;

        public DomainInfoResponseTests()
        {
            // TODO uncomment below to create an instance of DomainInfoResponse
            //instance = new DomainInfoResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainInfoResponse
        /// </summary>
        [Fact]
        public void DomainInfoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DomainInfoResponse
            //Assert.IsType<DomainInfoResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Fact]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }

        /// <summary>
        /// Test the property 'UseEncryption'
        /// </summary>
        [Fact]
        public void UseEncryptionTest()
        {
            // TODO unit test for the property 'UseEncryption'
        }

        /// <summary>
        /// Test the property 'HumanReadableName'
        /// </summary>
        [Fact]
        public void HumanReadableNameTest()
        {
            // TODO unit test for the property 'HumanReadableName'
        }

        /// <summary>
        /// Test the property 'HumanReadableNameDescription'
        /// </summary>
        [Fact]
        public void HumanReadableNameDescriptionTest()
        {
            // TODO unit test for the property 'HumanReadableNameDescription'
        }
    }
}
