/*
 * Agent API
 *
 * The Neuron® publishes an Agent API that can be used by agents that do not wish to, or are able to, connect to the Neuron® via any of the XMPP bindings available, such as standard binary  socket, websocket or Synchronous HTTP (BOSH). Via the Agent API, the agent is permitted to do  basic tasks, such as send messages, create Agent IDs, and sign contracts with such Agent IDs.  The Full API is 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TAG.Networking.Agent.Model;
using TAG.Networking.Agent.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TAG.Networking.Agent.Test.Model
{
    /// <summary>
    ///  Class for testing GetApplicationAttributesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetApplicationAttributesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetApplicationAttributesResponse
        //private GetApplicationAttributesResponse instance;

        public GetApplicationAttributesResponseTests()
        {
            // TODO uncomment below to create an instance of GetApplicationAttributesResponse
            //instance = new GetApplicationAttributesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetApplicationAttributesResponse
        /// </summary>
        [Fact]
        public void GetApplicationAttributesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetApplicationAttributesResponse
            //Assert.IsType<GetApplicationAttributesResponse>(instance);
        }

        /// <summary>
        /// Test the property 'PeerReview'
        /// </summary>
        [Fact]
        public void PeerReviewTest()
        {
            // TODO unit test for the property 'PeerReview'
        }

        /// <summary>
        /// Test the property 'NrReviewers'
        /// </summary>
        [Fact]
        public void NrReviewersTest()
        {
            // TODO unit test for the property 'NrReviewers'
        }

        /// <summary>
        /// Test the property 'NrPhotos'
        /// </summary>
        [Fact]
        public void NrPhotosTest()
        {
            // TODO unit test for the property 'NrPhotos'
        }

        /// <summary>
        /// Test the property 'Iso3166'
        /// </summary>
        [Fact]
        public void Iso3166Test()
        {
            // TODO unit test for the property 'Iso3166'
        }

        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Fact]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }
    }
}
