/*
 * Agent API
 *
 * The Neuron® publishes an Agent API that can be used by agents that do not wish to, or are able to, connect to the Neuron® via any of the XMPP bindings available, such as standard binary  socket, websocket or Synchronous HTTP (BOSH). Via the Agent API, the agent is permitted to do  basic tasks, such as send messages, create Agent IDs, and sign contracts with such Agent IDs.  The Full API is 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TAG.Networking.Agent.Model;
using TAG.Networking.Agent.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TAG.Networking.Agent.Test.Model
{
    /// <summary>
    ///  Class for testing PrivateXml
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PrivateXmlTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PrivateXml
        //private PrivateXml instance;

        public PrivateXmlTests()
        {
            // TODO uncomment below to create an instance of PrivateXml
            //instance = new PrivateXml();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PrivateXml
        /// </summary>
        [Fact]
        public void PrivateXmlInstanceTest()
        {
            // TODO uncomment below to test "IsType" PrivateXml
            //Assert.IsType<PrivateXml>(instance);
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Updated'
        /// </summary>
        [Fact]
        public void UpdatedTest()
        {
            // TODO unit test for the property 'Updated'
        }

        /// <summary>
        /// Test the property 'Xml'
        /// </summary>
        [Fact]
        public void XmlTest()
        {
            // TODO unit test for the property 'Xml'
        }
    }
}
