/*
 * Agent API
 *
 * The Neuron® publishes an Agent API that can be used by agents that do not wish to, or are able to, connect to the Neuron® via any of the XMPP bindings available, such as standard binary  socket, websocket or Synchronous HTTP (BOSH). Via the Agent API, the agent is permitted to do  basic tasks, such as send messages, create Agent IDs, and sign contracts with such Agent IDs.  The Full API is 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TAG.Networking.Agent.Model;
using TAG.Networking.Agent.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TAG.Networking.Agent.Test.Model
{
    /// <summary>
    ///  Class for testing Provider
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProviderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Provider
        //private Provider instance;

        public ProviderTests()
        {
            // TODO uncomment below to create an instance of Provider
            //instance = new Provider();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Provider
        /// </summary>
        [Fact]
        public void ProviderInstanceTest()
        {
            // TODO uncomment below to test "IsType" Provider
            //Assert.IsType<Provider>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'ReviewerId'
        /// </summary>
        [Fact]
        public void ReviewerIdTest()
        {
            // TODO unit test for the property 'ReviewerId'
        }

        /// <summary>
        /// Test the property 'External'
        /// </summary>
        [Fact]
        public void ExternalTest()
        {
            // TODO unit test for the property 'External'
        }

        /// <summary>
        /// Test the property 'IconUrl'
        /// </summary>
        [Fact]
        public void IconUrlTest()
        {
            // TODO unit test for the property 'IconUrl'
        }

        /// <summary>
        /// Test the property 'IconWidth'
        /// </summary>
        [Fact]
        public void IconWidthTest()
        {
            // TODO unit test for the property 'IconWidth'
        }

        /// <summary>
        /// Test the property 'IconHeight'
        /// </summary>
        [Fact]
        public void IconHeightTest()
        {
            // TODO unit test for the property 'IconHeight'
        }
    }
}
