/*
 * Agent API
 *
 * The Neuron® publishes an Agent API that can be used by agents that do not wish to, or are able to, connect to the Neuron® via any of the XMPP bindings available, such as standard binary  socket, websocket or Synchronous HTTP (BOSH). Via the Agent API, the agent is permitted to do  basic tasks, such as send messages, create Agent IDs, and sign contracts with such Agent IDs.  The Full API is 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Neuron.Agent.Client.OpenAPIDateConverter;

namespace Neuron.Agent.Model
{
    /// <summary>
    /// GetContractTokensBody
    /// </summary>
    [DataContract(Name = "GetContractTokensBody")]
    public partial class GetContractTokensBody : IEquatable<GetContractTokensBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetContractTokensBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetContractTokensBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetContractTokensBody" /> class.
        /// </summary>
        /// <param name="contractId">Identity of contract to get tokens for. (required).</param>
        /// <param name="offset">Offset into the list where response begins..</param>
        /// <param name="maxCount">Maximum number of tokens to return..</param>
        /// <param name="references">If token references is sufficient (true, default), or if entire tokens are to be returned (false)..</param>
        public GetContractTokensBody(string contractId = default(string), int offset = default(int), int maxCount = default(int), bool references = default(bool))
        {
            // to ensure "contractId" is required (not null)
            if (contractId == null)
            {
                throw new ArgumentNullException("contractId is a required property for GetContractTokensBody and cannot be null");
            }
            this.ContractId = contractId;
            this.Offset = offset;
            this.MaxCount = maxCount;
            this.References = references;
        }

        /// <summary>
        /// Identity of contract to get tokens for.
        /// </summary>
        /// <value>Identity of contract to get tokens for.</value>
        [DataMember(Name = "contractId", IsRequired = true, EmitDefaultValue = true)]
        public string ContractId { get; set; }

        /// <summary>
        /// Offset into the list where response begins.
        /// </summary>
        /// <value>Offset into the list where response begins.</value>
        [DataMember(Name = "offset", EmitDefaultValue = false)]
        public int Offset { get; set; }

        /// <summary>
        /// Maximum number of tokens to return.
        /// </summary>
        /// <value>Maximum number of tokens to return.</value>
        [DataMember(Name = "maxCount", EmitDefaultValue = false)]
        public int MaxCount { get; set; }

        /// <summary>
        /// If token references is sufficient (true, default), or if entire tokens are to be returned (false).
        /// </summary>
        /// <value>If token references is sufficient (true, default), or if entire tokens are to be returned (false).</value>
        [DataMember(Name = "references", EmitDefaultValue = true)]
        public bool References { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetContractTokensBody {\n");
            sb.Append("  ContractId: ").Append(ContractId).Append("\n");
            sb.Append("  Offset: ").Append(Offset).Append("\n");
            sb.Append("  MaxCount: ").Append(MaxCount).Append("\n");
            sb.Append("  References: ").Append(References).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetContractTokensBody);
        }

        /// <summary>
        /// Returns true if GetContractTokensBody instances are equal
        /// </summary>
        /// <param name="input">Instance of GetContractTokensBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetContractTokensBody input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ContractId == input.ContractId ||
                    (this.ContractId != null &&
                    this.ContractId.Equals(input.ContractId))
                ) && 
                (
                    this.Offset == input.Offset ||
                    this.Offset.Equals(input.Offset)
                ) && 
                (
                    this.MaxCount == input.MaxCount ||
                    this.MaxCount.Equals(input.MaxCount)
                ) && 
                (
                    this.References == input.References ||
                    this.References.Equals(input.References)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ContractId != null)
                {
                    hashCode = (hashCode * 59) + this.ContractId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Offset.GetHashCode();
                hashCode = (hashCode * 59) + this.MaxCount.GetHashCode();
                hashCode = (hashCode * 59) + this.References.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
