/*
 * Agent API
 *
 * The Neuron® publishes an Agent API that can be used by agents that do not wish to, or are able to, connect to the Neuron® via any of the XMPP bindings available, such as standard binary  socket, websocket or Synchronous HTTP (BOSH). Via the Agent API, the agent is permitted to do  basic tasks, such as send messages, create Agent IDs, and sign contracts with such Agent IDs.  The Full API is 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using TAG.Networking.Agent.Client;
using TAG.Networking.Agent.Api;
// uncomment below to import models
//using TAG.Networking.Agent.Model;

namespace TAG.Networking.Agent.Test.Api
{
    /// <summary>
    ///  Class for testing CryptoApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CryptoApiTests : IDisposable
    {
        private CryptoApi instance;

        public CryptoApiTests()
        {
            instance = new CryptoApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CryptoApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CryptoApi
            //Assert.IsType<CryptoApi>(instance);
        }

        /// <summary>
        /// Test CreateKey
        /// </summary>
        [Fact]
        public void CreateKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateKeyBody createKeyBody = null;
            //var response = instance.CreateKey(createKeyBody);
            //Assert.IsType<Stored>(response);
        }

        /// <summary>
        /// Test GetAlgorithms
        /// </summary>
        [Fact]
        public void GetAlgorithmsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object body = null;
            //var response = instance.GetAlgorithms(body);
            //Assert.IsType<AlgorithmsResult>(response);
        }

        /// <summary>
        /// Test GetPublicKey
        /// </summary>
        [Fact]
        public void GetPublicKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetPublicKeyBody getPublicKeyBody = null;
            //var response = instance.GetPublicKey(getPublicKeyBody);
            //Assert.IsType<GetPublicKeyResponse>(response);
        }
    }
}
