/*
 * Agent API
 *
 * The Neuron® publishes an Agent API that can be used by agents that do not wish to, or are able to, connect to the Neuron® via any of the XMPP bindings available, such as standard binary  socket, websocket or Synchronous HTTP (BOSH). Via the Agent API, the agent is permitted to do  basic tasks, such as send messages, create Agent IDs, and sign contracts with such Agent IDs.  The Full API is 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TAG.Networking.Agent.Client.OpenAPIDateConverter;

namespace TAG.Networking.Agent.Model
{
    /// <summary>
    /// NoteResult
    /// </summary>
    [DataContract(Name = "NoteResult")]
    public partial class NoteResult : IEquatable<NoteResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NoteResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected NoteResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="NoteResult" /> class.
        /// </summary>
        /// <param name="note">note (required).</param>
        public NoteResult(Dictionary<string, Object> note = default(Dictionary<string, Object>))
        {
            // to ensure "note" is required (not null)
            if (note == null)
            {
                throw new ArgumentNullException("note is a required property for NoteResult and cannot be null");
            }
            this.Note = note;
        }

        /// <summary>
        /// Gets or Sets Note
        /// </summary>
        [DataMember(Name = "Note", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, Object> Note { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NoteResult {\n");
            sb.Append("  Note: ").Append(Note).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NoteResult);
        }

        /// <summary>
        /// Returns true if NoteResult instances are equal
        /// </summary>
        /// <param name="input">Instance of NoteResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NoteResult input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Note == input.Note ||
                    this.Note != null &&
                    input.Note != null &&
                    this.Note.SequenceEqual(input.Note)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Note != null)
                {
                    hashCode = (hashCode * 59) + this.Note.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
