/*
 * Agent API
 *
 * The Neuron® publishes an Agent API that can be used by agents that do not wish to, or are able to, connect to the Neuron® via any of the XMPP bindings available, such as standard binary  socket, websocket or Synchronous HTTP (BOSH). Via the Agent API, the agent is permitted to do  basic tasks, such as send messages, create Agent IDs, and sign contracts with such Agent IDs.  The Full API is 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TAG.Networking.Agent.Client.OpenAPIDateConverter;

namespace TAG.Networking.Agent.Model
{
    /// <summary>
    /// PrivateXml
    /// </summary>
    [DataContract(Name = "PrivateXml")]
    public partial class PrivateXml : IEquatable<PrivateXml>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PrivateXml" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PrivateXml() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PrivateXml" /> class.
        /// </summary>
        /// <param name="created">When the information record was first created. (required).</param>
        /// <param name="updated">When the information record was last updated. (required).</param>
        /// <param name="xml">The XML to save. (required).</param>
        public PrivateXml(DateTime created = default(DateTime), DateTime updated = default(DateTime), string xml = default(string))
        {
            this.Created = created;
            this.Updated = updated;
            // to ensure "xml" is required (not null)
            if (xml == null)
            {
                throw new ArgumentNullException("xml is a required property for PrivateXml and cannot be null");
            }
            this.Xml = xml;
        }

        /// <summary>
        /// When the information record was first created.
        /// </summary>
        /// <value>When the information record was first created.</value>
        [DataMember(Name = "created", IsRequired = true, EmitDefaultValue = true)]
        public DateTime Created { get; set; }

        /// <summary>
        /// When the information record was last updated.
        /// </summary>
        /// <value>When the information record was last updated.</value>
        [DataMember(Name = "updated", IsRequired = true, EmitDefaultValue = true)]
        public DateTime Updated { get; set; }

        /// <summary>
        /// The XML to save.
        /// </summary>
        /// <value>The XML to save.</value>
        [DataMember(Name = "xml", IsRequired = true, EmitDefaultValue = true)]
        public string Xml { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PrivateXml {\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  Updated: ").Append(Updated).Append("\n");
            sb.Append("  Xml: ").Append(Xml).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PrivateXml);
        }

        /// <summary>
        /// Returns true if PrivateXml instances are equal
        /// </summary>
        /// <param name="input">Instance of PrivateXml to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PrivateXml input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Created == input.Created ||
                    (this.Created != null &&
                    this.Created.Equals(input.Created))
                ) && 
                (
                    this.Updated == input.Updated ||
                    (this.Updated != null &&
                    this.Updated.Equals(input.Updated))
                ) && 
                (
                    this.Xml == input.Xml ||
                    (this.Xml != null &&
                    this.Xml.Equals(input.Xml))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Created != null)
                {
                    hashCode = (hashCode * 59) + this.Created.GetHashCode();
                }
                if (this.Updated != null)
                {
                    hashCode = (hashCode * 59) + this.Updated.GetHashCode();
                }
                if (this.Xml != null)
                {
                    hashCode = (hashCode * 59) + this.Xml.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
